set echo
;  Copyright (c) 1995 IBK-Landquart-Switzerland. All rights reserved.
;
;  Module      :  PRINTDOC.SQL
;  Application :  TSS
;  Purpose     :  Print out online help
;  Author      :  Peter Koch, IBK
;
;  Date        Description                                 Who
;  --------------------------------------------------------------------------
;  June 1995   First release                               P.Koch, IBK
;
set pause
log prn.
?
exit
